---
apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: "home-automation"
commonLabels:
  app: "esp8266-dash-server"
resources:
  - "deployment.yml"
  - "service.yml"
  - "ingress.yml"
